### ISSUE TITLE
Add Mistral 7B model support

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#111]

**Comment by b41sh** [comment]
Hi, @flaneur2020 I'd like to work on this, can you assign this issue to me?

**Comment by flaneur2020** [comment]
@b41sh thank you for the contribution! you could download the mistral model from links like https://huggingface.co/TheBloke/Mistral-7B-v0.1-GGUF/tree/main 

i recommend using a q8_0 model, as it's the most optimized one and tested quantization format

(but i'm a bit afraid of there's a risk that we might already supported mistral model as it's also considered as a llama model, it need a confirmation though)

**Comment by flaneur2020** [comment]
I'm sorry, I grabbed this issue in #155 , mistral actually did not make difference with llama, but there's a bug in GQA implementation, it works well after this bug get resolved.

i've splitted more model support related tasks in: https://github.com/crabml/crabml/issues/157 , we can make some investigations together to add these models.

**Comment by b41sh** [comment]
Ok, I will continue work on those models.
