### ISSUE TITLE
Generate a logo for the repo

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#112]
feel free to use any AI image generator and paste it in the comment, we can take a vote to choose one : )

**Comment by frostming** [comment]
Some attempts by Ideogram:
![telegram-cloud-photo-size-4-6025210067244135140-y](https://github.com/crabml/crabml/assets/16336606/d14043e7-65d3-40c7-8ab6-f4b757c7d45a)
![telegram-cloud-photo-size-4-6024881674044683104-y](https://github.com/crabml/crabml/assets/16336606/549b42cd-b54a-49f1-9049-9b4e09400ac7)
![telegram-cloud-photo-size-4-6024962393660043973-y](https://github.com/crabml/crabml/assets/16336606/476ce29e-51cd-4bfe-813f-d822cf41304c)

The text can be ignored and the logo can be vectorized with https://vectorizer.ai/

**Comment by sundy-li** [comment]
chatgpt4：

![image](https://github.com/crabml/crabml/assets/3325189/b6e19d98-edc1-4f27-b801-f014b876094c)

**Comment by xiaguan** [comment]
![crabml](https://github.com/crabml/crabml/assets/26018364/502732da-96ef-420d-a452-122488f56744)

**Comment by PsiACE** [comment]
![Designer (1)](https://github.com/crabml/crabml/assets/36896360/0471a74e-dbd5-42f6-a6fb-2c302971f3d2)

**Comment by xiaji** [comment]
![Uploading x1aji_Create_a_logo_for_crabml_a_project_reimplementing_GGML_wi_313c1470-7c2c-4ea7-b19c-23cf92d551c7.png…]()

**Comment by xiaji** [comment]
![x1aji_Create_a_logo_for_crabml_a_project_reimplementing_GGML_wi_313c1470-7c2c-4ea7-b19c-23cf92d551c7](https://github.com/crabml/crabml/assets/1174153/86ba3753-3079-424f-9f72-6e343881263b)

**Comment by guojidan** [comment]
> ![x1aji_Create_a_logo_for_crabml_a_project_reimplementing_GGML_wi_313c1470-7c2c-4ea7-b19c-23cf92d551c7](https://private-user-images.githubusercontent.com/1174153/312825243-86ba3753-3079-424f-9f72-6e343881263b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTcyNzIsIm5iZiI6MTcxMDQxNjk3MiwicGF0aCI6Ii8xMTc0MTUzLzMxMjgyNTI0My04NmJhMzc1My0zMDc5LTQyNGYtOWY3Mi02ZTM0Mzg4MTI2M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTE0OTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2UxODFhMTJkY2ZhN2JjMmJlNThiMjViOWIyOGEzYmZkZWMyMmNkZWU3OTNkNTIzMGNkMGFhY2ZkYTY1OTA1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B4o2VVcA5Xpd8p3awRBG7G4H7xBEm-_ONkHbx_RTnds)

hhh, so cute, I love it so much ! 😆

**Comment by xiaji** [comment]
> > ![x1aji_Create_a_logo_for_crabml_a_project_reimplementing_GGML_wi_313c1470-7c2c-4ea7-b19c-23cf92d551c7](https://private-user-images.githubusercontent.com/1174153/312825243-86ba3753-3079-424f-9f72-6e343881263b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTcyNzIsIm5iZiI6MTcxMDQxNjk3MiwicGF0aCI6Ii8xMTc0MTUzLzMxMjgyNTI0My04NmJhMzc1My0zMDc5LTQyNGYtOWY3Mi02ZTM0Mzg4MTI2M2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTRUMTE0OTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2UxODFhMTJkY2ZhN2JjMmJlNThiMjViOWIyOGEzYmZkZWMyMmNkZWU3OTNkNTIzMGNkMGFhY2ZkYTY1OTA1MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.B4o2VVcA5Xpd8p3awRBG7G4H7xBEm-_ONkHbx_RTnds)
> 
> hhh, so cute, I love it so much ! 😆

even there are some scores on the letter C

**Comment by flaneur2020** [comment]
we'll close the voting in this weekend, the logo in which comment with highest interactions will be choosen 😊

**Comment by flaneur2020** [comment]
after deduplicated, @PsiACE 's logo has the highest vote, we'll choose it as the first logo, congrats!
