### ISSUE TITLE
handle UTF-8 properly in the BPE tokenizer

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#134]
I believe there're something wrong with handling utf-8 in the BPE tokenizer. I've met several times about utf-8 errors during text generation, but i'm not sure how to reproduce this error.

I suppose that we can find out what's wrong after get a deep understanding about the BPE algorithm from https://github.com/karpathy/minbpe

**Comment by PsiACE** [comment]
Oh, I can reproduce it. I'll double-check.

**Comment by zxch3n** [comment]
Isn't it possible to be caused by invalid UTF8 string?
