### ISSUE TITLE
SIMD in Q4_1

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#160]

**Comment by b41sh** [comment]
I would like to work on this issue @flaneur2020

**Comment by flaneur2020** [comment]
@b41sh thank you! you could reference code from: https://github.com/crabml/crabml/blob/main/crabml-core/src/backends/cpu/buf/buf_q8_0.rs#L222 and the relevant quantization algorithm from the ggml repo like: https://github.com/ggerganov/ggml/blob/master/src/ggml-quants.c#L4051
