### ISSUE TITLE
Add x86_64 support

### ISSUE THREAD

**Issue by Xuanwo** [crabml/crabml#38]
crabml doesn't work on x86_64 yet, we should add x86_64 support first.

**Comment by Xuanwo** [comment]
f32 is supported, q8 is ongoing

**Comment by flaneur2020** [comment]
after https://github.com/crabml/crabml/pull/43 get merged, IMHO this issue have been resolved :heart:

**Comment by Xuanwo** [comment]
DONE, let's move!
