### ISSUE TITLE
Support for wasm32 target

### ISSUE THREAD

**Issue by apepkuss** [crabml/crabml#59]
Hello guys,

Do you have any plan to support `wasm32` target? 

Thanks!

**Comment by Xuanwo** [comment]
> Do you have any plan to support `wasm32` target?

Yep! We do want to support `wasm32` target. That's part of reason why we support `wgpu`.

**Comment by apepkuss** [comment]
May I have your wechat or email? Thanks!

**Comment by Xuanwo** [comment]
> May I have your wechat or email? Thanks!

We prefer to chat in public, so feel free to reach out on GitHub or join our [Discord server](https://discord.gg/wbzqddT3QC).

But if you need something discussed privately, it's totally fine to email me at `github AT xuanwo.io`.

**Comment by apepkuss** [comment]
I'm in your discord server. Thank you so much!
