### ISSUE TITLE
Add Support For GGUFv3

### ISSUE THREAD

**Issue by PsiACE** [crabml/crabml#64]

**Comment by flaneur2020** [comment]
Oh, I've already added support in https://github.com/crabml/crabml/pull/57.

It seems that GGUFv3 primarily introduced support for big endian machines and did not introduce any changes on the little endian machines' side. I guess we can defer the actual support for big endian machines to later and, for now, just ensure it can read v3 without errors.

**Comment by flaneur2020** [comment]
now i believe crabml can inference the GGUFv3 models without error in the main branch.
