### ISSUE TITLE
Add K quants support to CPU tensor buf

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#75]
i still haven't learned the details about what 'K-quants' means yet, but it seems that K-quant can add more accuracy to the low-bit quantized data.

we only need consider the cpu part right now, you can just implement the 'fallback' version (no SIMD) of code which is easier to be implemented.

The following new quantization types are added to ggml:

> GGML_TYPE_Q2_K - "type-1" 2-bit quantization in super-blocks containing 16 blocks, each block having 16 weight. Block scales and mins are quantized with 4 bits. This ends up effectively using 2.5625 bits per weight (bpw)
> GGML_TYPE_Q3_K - "type-0" 3-bit quantization in super-blocks containing 16 blocks, each block having 16 weights. Scales are quantized with 6 bits. This end up using 3.4375 bpw.
> GGML_TYPE_Q4_K - "type-1" 4-bit quantization in super-blocks containing 8 blocks, each block having 32 weights. Scales and mins are quantized with 6 bits. This ends up using 4.5 bpw.
> GGML_TYPE_Q5_K - "type-1" 5-bit quantization. Same super-block structure as GGML_TYPE_Q4_K resulting in 5.5 bpw
> GGML_TYPE_Q6_K - "type-0" 6-bit quantization. Super-blocks with 16 blocks, each block having 16 weights. Scales are quantized with 8 bits. This ends up using 6.5625 bpw
> GGML_TYPE_Q8_K - "type-0" 8-bit quantization. Only used for quantizing intermediate results. The difference to the existing Q8_0 is that the block size is 256. All 2-6 bit dot products are implemented for this quantization type.

- [x] #76
- [x] #77
- [x] #80
- [x] #81
- [x] #82
- [x] #83

links might be useful:

- https://github.com/ggerganov/llama.cpp/pull/1684
- https://old.reddit.com/r/LocalLLaMA/comments/14gjz8h/i_have_multiple_doubts_about_kquant_models_and/

**Comment by flaneur2020** [comment]
it seems that the K-Quant types have an extra "superblock" above the normal blocks.

**Comment by guojidan** [comment]
Machine learning is a new knowledge for most people, so I think we can share some of our own learning paper && project && blog to help newcomers quickly participate in projects 🤔

**Comment by flaneur2020** [comment]
@guojidan we'll actively sync the new papers, news, and optimization tips into this Discord channel: https://discord.com/invite/wbzqddT3QC

we'll also actively respond to your questions about anything we've learned. don't hesitate to talk here!
