### ISSUE TITLE
Support K-quants for Q5

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#81]

**Comment by gobraves** [comment]
Let me take it.

**Comment by flaneur2020** [comment]
@gobraves thank you a lot, i'm thrilled to have your contribution

**Comment by AuruTus** [comment]
hi @gobraves , the q5k may use the `make_qkx1_quants(...)` function to calculate scales. Since I already implement it with q2k, you can use it by importing it from `qkk` mod.
