### ISSUE TITLE
Support inferencing X's Grok model

### ISSUE THREAD

**Issue by flaneur2020** [crabml/crabml#99]
![Screenshot 2024-03-11 at 17 11 34](https://github.com/crabml/crabml/assets/129800/6e5cdbc8-1dd9-4603-8fb7-ca70552f45f2)

**Comment by Xuanwo** [comment]
wow

**Comment by flaneur2020** [comment]
sadly grok model is way toooo big for us, we can consider re-open this issue when we have more time on it.
